Improvements in JS import - more conforming handling
- Only accept absolute or relative paths (/, ./, ../), disallow bare words
- Correctly resolve true path of imported script based on CWD of importer

diff --git a/src/tests/test.sh.in b/src/tests/test.sh.in
--- a/src/tests/test.sh.in
+++ b/src/tests/test.sh.in
@@ -163,15 +163,52 @@ do_test_socket test_cmodule.conf
 
 echo "With node: $RRR_WITH_NODE"
 if test "x$RRR_WITH_NODE" != 'xno'; then
-	if ! ../rrr_js < test_import.js; then
+	PWD=`pwd`
+	SCRIPT_SUCCESS=test_import_success.js
+	SCRIPT_FAIL=test_import_fail.js
+	TAIL=".then(() => {console.log('- OK')}).catch((msg) => {console.critical('- Loading failed: ' + msg)})";
+
+	# Failing imports test
+	echo "Test failing import"
+	if ! ../rrr_js module < $SCRIPT_FAIL; then
 		# Import test failed
 		exit 1
 	fi
 
+	# Load module
+	echo "Test successful import"
+	if ! ../rrr_js module < $SCRIPT_SUCCESS; then
+		# Import test failed
+		exit 1
+	fi
+
+	# Load module with import statement as script (should fail)
+	echo "Test import statement in script"
+	if ../rrr_js script < $SCRIPT_SUCCESS; then
+		# Import test failed
+		exit 1
+	fi
+
+	# Load with absolute path
+	echo "Test absolute path"
+	if ! echo "import('$PWD/$SCRIPT_SUCCESS')$TAIL;" | ../rrr_js module; then
+		# Import test failed
+		exit 1
+	fi
+	echo
+
+	# Load with relative path
+	echo "Test relative path"
+	if ! echo "import('../tests/$SCRIPT_SUCCESS')$TAIL;" | ../rrr_js module; then
+		# Import test failed
+		exit 1
+	fi
+	echo
+
 	./test_import_support.sh
 	case $? in
 		0)
-			if ! ../rrr_js < test_json_import.js; then
+			if ! ../rrr_js module < test_json_import.js; then
 				# Dynamic json import test failed
 				exit 1
 			fi
